services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules/
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_PRISMA_URL: postgres://postgres:password@db:5432/saldo
      POSTGRES_URL_NON_POOLING: postgres://postgres:password@db:5432/saldo


  db:
    image: postgres:16
    ports:
      - "3006:5432"    
    environment:
      POSTGRES_DB: saldo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
