export const EXPECTED_HOURS_PER_DAY = 7.5;
export const EXPECTED_MINUTES_LUNCH_BREAK = 30;
export const NEW_WORKLOG_DEFAULT_FROM = '08:00';
export const NEW_WORKLOG_DEFAULT_TO = '16:00';
export const NEW_WORKLOG_DEFAULT_SUBTRACT_LUNCH = true;
